In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4]) # 1차원 배열 생성 
print(A)

[1 2 3 4]


In [3]:
print(np.ndim(A)) #배열의 차원수를 알려줘 !

1


In [4]:
print(A.shape) #배열의 차원의 크기를 튜플 형태로 알려줘 !

(4,)


In [5]:
print(A.shape[0]) #위와 차이점은 , 이게 있고 없고 인데 ,, 내가 볼땐 A.shape 값의 0번째 index를 알려달라는거 같아 

4


In [6]:
B = np.array([[1,2,3] , [3,4,5] , [6,7,9]]) #3차원 배열 생성
print(B)

[[1 2 3]
 [3 4 5]
 [6 7 9]]


In [7]:
print(np.ndim(B))

2


In [8]:
print(B.shape)

(3, 3)


In [9]:
print(B.shape[0])

3


In [10]:
import numpy as np

In [11]:
A = np.array([[1,2] , [5,6]]) #2차원으로 A 배열 생성
print(A.shape)

(2, 2)


In [12]:
B = np.array([[92,91] , [8,65]])
print(B.shape)

(2, 2)


In [13]:
print(np.dot(A,B)) #A와 B의 곱을 알려주는 np.dot(n1 , n2)

[[108 221]
 [508 845]]


In [14]:
import numpy as np

In [15]:
A = np.array([[1,2] , [5,6]])
print(A.shape)
print(A.shape[0])

(2, 2)
2


In [16]:
B = np.array([[1,2] , [3,4]])
print(B.shape)
print(B.shape[0])

(2, 2)
2


In [17]:
print(np.dot(A,B))

[[ 7 10]
 [23 34]]


In [18]:
C = np.array([[1,2] , [3,4]])
print(C.shape)
print(C.shape[0])

(2, 2)
2


In [19]:
print(np.dot(A, C))

[[ 7 10]
 [23 34]]


In [20]:
X = np.array([1,2])
print(X.shape)

(2,)


In [21]:
W = np.array([[1,3,5] , [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [22]:
print(W.shape)

(2, 3)


In [24]:
Y = np.dot(X, W) #X 랑 W 둘다 곱한걸 Y라하자 !
print(Y)

[ 5 11 17]


In [28]:
X = np.array([1.0 , 0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)

print(A1)
print(Z1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
