In [41]:
import numpy as np

In [42]:
A = np.array([1,2,3,4]) # 1차원 배열 생성 
print(A)

[1 2 3 4]


In [43]:
print(np.ndim(A)) #배열의 차원수를 알려줘 !

1


In [44]:
print(A.shape) #배열의 차원의 크기를 튜플 형태로 알려줘 !

(4,)


In [45]:
print(A.shape[0]) #위와 차이점은 , 이게 있고 없고 인데 ,, 내가 볼땐 A.shape 값의 0번째 index를 알려달라는거 같아 

4


In [46]:
B = np.array([[1,2,3] , [3,4,5] , [6,7,9]]) #3차원 배열 생성
print(B)

[[1 2 3]
 [3 4 5]
 [6 7 9]]


In [47]:
print(np.ndim(B))

2


In [48]:
print(B.shape)

(3, 3)


In [49]:
print(B.shape[0])

3


In [50]:
import numpy as np

In [51]:
A = np.array([[1,2] , [5,6]]) #2차원으로 A 배열 생성
print(A.shape)

(2, 2)


In [52]:
B = np.array([[92,91] , [8,65]])
print(B.shape)

(2, 2)


In [53]:
print(np.dot(A,B)) #A와 B의 곱을 알려주는 np.dot(n1 , n2)

[[108 221]
 [508 845]]


In [54]:
import numpy as np

In [55]:
A = np.array([[1,2] , [5,6]])
print(A.shape)
print(A.shape[0])

(2, 2)
2


In [56]:
B = np.array([[1,2] , [3,4]])
print(B.shape)
print(B.shape[0])

(2, 2)
2


In [57]:
print(np.dot(A,B))

[[ 7 10]
 [23 34]]


In [58]:
C = np.array([[1,2] , [3,4]])
print(C.shape)
print(C.shape[0])

(2, 2)
2


In [59]:
print(np.dot(A, C))

[[ 7 10]
 [23 34]]


In [60]:
X = np.array([1,2])
print(X.shape)

(2,)


In [61]:
W = np.array([[1,3,5] , [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [62]:
print(W.shape)

(2, 3)


In [63]:
Y = np.dot(X, W) #X 랑 W 둘다 곱한걸 Y라하자 !
print(Y)

[ 5 11 17]
