In [1]:
import numpy as np

In [2]:
a = np.array([0.3 , 2.9 , 4.0])

exp_a = np.exp(a) #지수 함수
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [4]:
sum_exp_a = np.sum(exp_a) #지수 함수의 합
print(sum_exp_a)

74.1221542101633


In [6]:
y = exp_a / sum_exp_a
print(y) # 지수 함수와 함수의 합을 나눈 값

[0.01821127 0.24519181 0.73659691]


In [8]:
#소프트맥스 함수 구현

z = np.array([[0.53 , 0.421] , [0.242 , 0.11] , [0.125 , 0.363]])

def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

print(softmax(z)) # 그냥 출력해본것

[[0.20761036 0.18617053]
 [0.15565828 0.13640973]
 [0.1384713  0.17567981]]


In [6]:
import numpy as np

a = np.array([1000 , 1010 , 990])
np.exp(a) / np.sum(np.exp(a))

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) #오버플로 대책
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

<ipython-input-6-3ec7ff7304ad>:4: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
<ipython-input-6-3ec7ff7304ad>:4: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


In [9]:
a = np.array([2.7 , 0.2 , 5.1])
y = softmax(a)

print(y)

print(np.sum(y))

[0.08260871 0.00678094 0.91061036]
1.0
